sudo: required
services:
  - docker

before_install:
  - docker build -t chaitanyasathi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chaitanyasathi/react-test npm test -- --coverage

after_success:
  - docker build -t chaitanyasathi/multi-client ./client
  - docker build -t chaitanyasathi/multi-nginx ./nginx
  - docker build -t chaitanyasathi/multi-server ./server 
  - docker build -t chaitanyasathi/multi-worker ./worker 

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hubs
  - docker push chaitanyasathi/multi-client
  - docker push chaitanyasathi/multi-server
  - docker push chaitanyasathi/multi-nginx
  - docker push chaitanyasathi/multi-nginx  

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-911626906306
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY